#
# Copyright 2011-2015 B2i Healthcare Pte Ltd, http://b2i.sg
#

# Redirects configuration directory to a random directory under OSGI installation directory
configurationDirectory: testing/rest/configuration

# Redirectes resources directory to have a clean H2 content
resourceDirectory: testing/rest/resources

# necessary to connect one user to the system otherwise Snow Owl startup fails
systemUser: true

identity:
  providers:
    - file:
        name: users
