#
# Copyright 2011-2017 B2i Healthcare Pte Ltd, http://b2i.sg
#

# Redirects configuration directory to a random directory under OSGI installation directory
configurationDirectory: testing/rest/configuration

# Redirects resources directory to have a clean H2 content
resourceDirectory: testing/rest/resources

# necessary to connect one user to the system otherwise Snow Owl startup fails
systemUser: true

auth:
  type: PROP_FILE
  
snomed:
  # Disable concrete domains, we are going to import the required concepts to an extension
  concreteDomainSupport: false
  ids:
    strategy : EMBEDDED
  classification:
    maxReasonerCount: 1
    defaultReasoner: org.semanticweb.elk.elk.reasoner.factory
    showReasonerUsageWarning: false
    maxReasonerCount: 1
    maxReasonerResults: 20
    maxReasonerRuns: 10000
    externalService:
      url: http://localhost:8089
      userName: extServiceUserName
      password: extServicePassword
      numberOfPollTries: 1
      timeBetweenPollTries: 10
  
metrics:
  enabled: true

fileAuth:
  users:
    -
      username: snowowl
      password: snowowl